title:             Storytelling Fellows Podcasting
email:             libstory@uw.edu
description:       A UW Libraries online workshop for podcasting storytellers
author:            Podcasting Teaching Team
baseurl:           "/"
url:               "http://libstory.github.io"

# Social Profiles
twitter_username:
github_username: libstory
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
